### ISSUE TITLE
Improve script B

### ISSUE THREAD

**Issue by a-tze** [crs-tools/tracker#109]
*Issue migrated from trac ticket # 109*

**component:** contrib | **priority:** minor | **keywords:** scripts, worker, fuse, mount

#### 2015-08-17 13:03:59: @a-tze created the issue

___
Two things can be improved for finding errors:

  - Catch output from fuse-* and put it into the ticket comment (e.g. "WARNING: to few files found")
  - there should be a ffprobe run on the uncut.ts to check length etc.

**Comment by jjeising** [comment]
@crs-tools/scripts this should probably move?

**Comment by a-tze** [comment]
moved to scripts
