### ISSUE TITLE
Create API to set ticket priority

### ISSUE THREAD

**Issue by a-tze** [crs-tools/tracker#144]
*Issue migrated from trac ticket # 144*

**component:** rpc | **priority:** minor

**Comment by pegro** [comment]
@j-licht Is this still required? What would be the use-case, where a script would need to change ticket priorities?

**Comment by jjeising** [comment]
@j-licht Could you give an update?

**Comment by j-licht** [comment]
I think there is no use case for this now.

**Comment by jjeising** [comment]
Thanks for the feedback!
