### ISSUE TITLE
Add Python C3TT client to contribution folder?

### ISSUE THREAD

**Issue by saerdnaer** [crs-tools/tracker#147]
Add  https://github.com/voc/publishing/blob/master/src/api_client/c3tt_rpc_client.py (or later  https://github.com/voc/c3tt-worker) to https://github.com/crs-tools/tracker/tree/master/contribution ?

**Comment by jjeising** [comment]
We determined that we would like to move the API libs from contribution to their own repositories.

I've created [crs-tools/tracker-xmlrpc-python](https://github.com/crs-tools/tracker-xmlrpc-python) and added you and @derpeter as contributors.
