### ISSUE TITLE
Don't lose cutpoints when extending the timeline

### ISSUE THREAD

**Issue by v0tti** [crs-tools/tracker#151]
If a recording is cut and is not long enough the previously set cutpoints should persist.

The Operator could already have spend a lot of time looking for the inpoint before noticing that the recording is not long enough. Currently the inpoint would be lost and the operator has to set it again.

**Comment by a-tze** [comment]
This is difficult to achieve with current architecture, since the tracker application has no access to the info in the fuse mount. 
Possible solution: set a property on the ticket that tells the mount worker to save and restore the cutmarks before unmount/after mount.

**Comment by jjeising** [comment]
Wouldn't we also enable easy remounts when always restoring cut marks when they exist?

**Comment by a-tze** [comment]
Looking at the mounts: yes. Looking at the ticket states: no. The ticket needs to be reset to recorded and then the previous state information is lost.

**Comment by jjeising** [comment]
> then the previous state information is lost
Why do we need the previous state? It should be safe to always restore if the properties exist, shouldn't it?

**Comment by a-tze** [comment]
In the use case "restore mounts": if it was already cut, then it should end up in finalized without manual interaction and maybe without going through finalizing.
While in the use case of extending, it of course should end up in prepared (this happens right now and is ok).

**Comment by jjeising** [comment]
Okay, we probably need a separate solution to trigger remounts (ideally without leaving finalized). But cut marks could always be restored.

**Comment by a-tze** [comment]
Agree, therefore I already created https://github.com/crs-tools/crs-scripts/issues/4 and came to the conclusion that there should be no problem when always restoring cutmarks.

For documentation: there is a script that can manually restore mounts from all tickets in finalized:
https://github.com/crs-tools/crs-scripts/blob/master/scripts/restore-fuse-mounts.pl but of course there is no web UI for that.
