### ISSUE TITLE
Fahrplan ID length, readability and memorability

### ISSUE THREAD

**Issue by jjeising** [crs-tools/tracker#155]
Last years congress' Fahrplan IDs ranged from ~8700 to ~9300. With other events during the year we'll definitely have five digit IDs soon.

While this is technically no problem, readability and memorability suffer with more than four digits (reading _10-532_ may still work, but doesn't suggest itself immediately). Fahrplan IDs play are currently also prominently displayed in the tracker interface, where currently there is only space for four digits. This can be expanded but we should think about what format we like before touching this area.

There are currently two suggestions for abbreviations:

- Convert all incoming Fahrplan IDs to hexadecimal. This could maybe even be coordinated with frab. Examples:

Old | Option 1
-- | --
1147 | 47B
5941 | 1735
8714 | 220A
9297 | 2351
11293 | 2C1D

Maximum number of IDs with four characters: 65.535

An issue here could be confusion with old or existing IDs outside of our services, if this is not done on frab level.

- Prefix existing IDs with a letter. Optional shorten by one character.

Old | Option 2 | Option 3
-- | -- | --
1147 | A1147 | A147
5941 | A5951 | E951
8714 | A8714 | H951
9297 | A9297 | I297
11293 | B1293 | K293

Maximum number of IDs with five characters: 259.974
Maximum number of IDs with four characters: 25.974

Option 2 has five characters, but the first character should not change during an event, so four numbers are still nonambigious. Also _B-1293_ is a natural breakup.

Ideas, opinions and feelings? @derpeter @saerdnaer @a-tze @manno

**Comment by derpeter** [comment]
I would vote for keeping frab and tracker in sync regarding the id representation. I can work with 5 digits but i we probably will never exhaust that number space. Also we only have this problem at congress.

**Comment by jjeising** [comment]
> Also we only have this problem at congress.

Once we crossed this affects all events managed with CCCs frab instance.

**Comment by manno** [comment]
I understand human readable IDs are an important feature. However frab currently uses the database ID. Changing this acrosss the UI seems like a complicated change.

**Comment by a-tze** [comment]
I like the thoughts being made. But from the perspective of the work on an event I have to say that the human brain kills redundant digits anyway. If there is a 4 day congress and you swim in numbers from 10.000 to 11.999, the first digit is just ignored anyway.
As I said, I like those ideas / IDs ;) but the straight and easy way is extending the tracker layout for five digits and be happy with that for a very long time.

**Comment by jjeising** [comment]
We now have five digit ids, going to close this until further issues arise.
