### ISSUE TITLE
Change effective privileges in some cases

### ISSUE THREAD

**Issue by a-tze** [crs-tools/tracker#156]
Especially users having "high" roles but being restricted to some projects do have effectively access to many things they shouldnt have. Especially the global settings like workers, encoding profile (contents/properties) etc. should be inaccessible to a user that is restricted to projects.

**Comment by jjeising** [comment]
@a-tze With the new restricted superuser role, is this still an issue?

**Comment by a-tze** [comment]
@jjeising Yes. It seems that restricted superusers can create new users and give them access to other projects or even admin privileges.

**Comment by a-tze** [comment]
Looks good
