### ISSUE TITLE
Comment view_serviceable_tickets

### ISSUE THREAD

**Issue by jjeising** [crs-tools/tracker#166]
As the complexity of `view_serviceable_tickets` was increased in 154cee0e53f4418a68adda29484212ab1dcf3962 and b9fd43588ab0f06b40b22791af54324aa0cc1f3e it would probably be advisable to add some comments with an explanation for table aliases, special JOINs like `epv2` and the general intent.

**Comment by a-tze** [comment]
@jjeising I think this is fixed now with #169, what do you think? Forgot to close via commit message.

**Comment by jjeising** [comment]
Yes, thank you.
