### ISSUE TITLE
Dependent tickets fail to release when their master is not released

### ISSUE THREAD

**Issue by zuntrax** [crs-tools/tracker#179]
When the "trigger state" for starting dependent tickets is not set to "released", the dependent ticket can be assigned to a releasing worker before the master ticket. This leads to a failed release.

A workaround recommended by @a-tze is to increase the priority of the master encoding profile.

Nevertheless, I think there should be a check to prevent this.

**Comment by a-tze** [comment]
It's not luck, because it references only this special situation (voctoweb publishing). There the priority works reliable because there is only one worker instance. And yes, of course the "real fix" is totally out of scope for the tracker.

**Comment by jjeising** [comment]
> There the priority works reliable because there is only one worker instance.

… and because the dependent state is *ready to release*? Otherwise it would still be possible to have a dependee in *postprocessing* while the dependent is ready.

Closing this, please open a ticket for [voc/publishing](https://github.com/voc/publishing/issues).
