### ISSUE TITLE
Newly created project disappears because user doesn't have rights to see it

### ISSUE THREAD

**Issue by robbi5** [crs-tools/tracker#181]
I've just tried to create a fresh project. The "add project" Button is usable, `/project/create` shows the  form and creates the project. But the redirect to the freshly created project then ends on `/{slug}/settings` which only shows "Page not found".

It looks like even if my user has the rights to create a project, that newly created project doesn't get added to the projects my user has access to.

**Comment by jjeising** [comment]
Thanks for the report!

This is sort of a known issue, arisen from the idea that people need access to encoding tickets, but still have limited projects.

We should add a project administrator role beside the superuser and remove limiting for superusers.

**Comment by saerdnaer** [comment]
This happens only when a restricted superuser creates a new project. Why not automaticallly add the user itself, to the project while create it, when the user is restricted?

**Comment by jjeising** [comment]
_Restricted superuser_ (project administrator) is now allowed to manage all aspects of a project, but cannot edit encoding profiles. _Superuser_ cannot be restricted anymore.

**Comment by saerdnaer** [comment]
> Superuser cannot be restricted anymore.
Can you explain the reason behind this? There are a few use cases where it was helpful to give the superuser rights to a local event admin, without giving them the right to modify other projects.

**Comment by jjeising** [comment]
> There are a few use cases where it was helpful to give the superuser rights to a local event admin, without giving them the right to modify other projects.

Please check the rights of the _Restricted superuser_ (project administrator) role.
