### ISSUE TITLE
Encoding ticket of profile with dependency should not be serviceable, if dependee ticket doesn't exist?!

### ISSUE THREAD

**Issue by pegro** [crs-tools/tracker#182]
As far as I could see from reading the code, nothing prevents from having tickets of encoding profiles, which have a dependency profile configured but no tickets for that profile exist.

And in view_serviceable_tickets the LEFT JOINs together with various COALESCE statements render those tickets serviceable, although their input probably doesn't exist.

Or did I miss something?

**Comment by jjeising** [comment]
I did a quick local test, the encoding ticket appears in the queue, even if the dependent profile was not added to the project. Should probably be fixed in the view first. We might also add an error when a depending encoding profile is added to the project, without its parent?

**Comment by pegro** [comment]
Yeah, sounds like a good idea.
Also credit to @j-licht for finding this bug.

**Comment by jjeising** [comment]
> if you like you could add such a warning toaster(?) directly to the 182-something branch, where I just opened a PR for this.

Added a warning in #183.
