### ISSUE TITLE
Public API - Released talks: Add filter for master encoding tickets

### ISSUE THREAD

**Issue by saerdnaer** [crs-tools/tracker#185]
I think we should filter the output of https://github.com/crs-tools/tracker/blob/master/src/Application/Controller/API.php#L39 to only output master encoding tickets by default or by optional URL parameter

**Comment by a-tze** [comment]
Why not just group the output by fahrplan_id on the consumer side?

**Comment by jjeising** [comment]
What are the current known consumers of this API? Why do they need filtering and which need all releases?

**Comment by saerdnaer** [comment]
The typical use case is to get a mapping of the talk id to the corresponding youtube urls, which is empty for the sub-formats.

**Comment by jjeising** [comment]
I currently tend to a wontfix in this versions of the API. I would like to extend the API and provide a more helpful structure (e.g. formats grouped by ticket). This new API may also include filtering, but probably not, as there are currently not many consumers.

**Comment by saerdnaer** [comment]
Okay, created a new issue to discuss a new api #196 and closing this one
