### ISSUE TITLE
Resetting tickets (and their children)

### ISSUE THREAD

**Issue by j-licht** [crs-tools/tracker#188]
For our use case, it's useful to have resetTicket methode in the API.
To allow re-encode a video without re-creating the encoding ticket.
The reset should set a ticket back to its initial state.
So after that commenceState has to be called to get things happen again.
When resetting a meta ticket all encoding childs should also be reset.
When resetting a 'master' encoding ticket, all tickets of a depending profile should be reset too.

Do we implement this as a model function or stored procedure?

**Comment by saerdnaer** [comment]
Are you aware of the the following feature – you might be able to reuse it for your goals
<img width="915" alt="image" src="https://user-images.githubusercontent.com/40266/47267722-ef5c5480-d547-11e8-85f3-65fb9d1473f4.png">

**Comment by jjeising** [comment]
> Do we implement this as a model function or stored procedure?

Currently we have [`Ticket::resetSource`](https://github.com/crs-tools/tracker/blob/master/src/Application/Model/Ticket.php#L804), which does some similar things, but is very specific.

For consistency and transactional reasons I think this should be moved to a stored procedure, which should also support a desired state for the recording ticket (exact state, first state before or first state after, if there are none before) and maybe even for the encoding tickets.

**Comment by jjeising** [comment]
> What did you mean with before and after? Before which thing or state?

As arbitrary states can be disabled per project the target (to reset to) state has to computed from a desired hardcoded state. Example: desired state for reset is _ready to encode_, if it is disabled, the next state after should probably be selected.
I first thought about resetting to the previous state for disabled states, but this wouldn't be helpful.

**Comment by pegro** [comment]
How would you provide these desired states for different ticket types to a stored procedure?
Having explicit parameters for each type? So we'd have to extend the API every time (although it didn't happen for a long time) we add a ticket type?
