### ISSUE TITLE
Missing foreign key references

### ISSUE THREAD

**Issue by saerdnaer** [crs-tools/tracker#204]
When I looked into the database schema, I found following "missing" foreign key refernces – was this accidental or by design?

```sql
ALTER TABLE tbl_comment
  ADD FOREIGN KEY ("ticket_id") REFERENCES tbl_ticket("id"),
  ADD FOREIGN KEY ("handle_id") REFERENCES tbl_handle("id");


ALTER TABLE tbl_log
  ADD FOREIGN KEY ("ticket_id") REFERENCES tbl_ticket("id"),
  ADD FOREIGN KEY ("handle_id") REFERENCES tbl_handle("id");


ALTER TABLE tbl_ticket_property 
  ADD FOREIGN KEY ("ticket_id") REFERENCES tbl_ticket("id");

```

**Comment by a-tze** [comment]
I dont understand. Where did you look and where is it missing?

For example, the first FK constraint you mention is here:

https://github.com/crs-tools/tracker/blob/master/src/Application/Migrations/07_comments.sql#L14

The second one has been replaced by a trigger function.

**Comment by saerdnaer** [comment]
I used a datebase backup of the voc instance, and have to check the schema once I create a new database instance from scratch.

**Comment by jjeising** [comment]
If you still think there is something missing, please reopen.
