### ISSUE TITLE
Hide children for closed meta tickets

### ISSUE THREAD

**Issue by saerdnaer** [crs-tools/tracker#205]
When adding new encoding tickets to a exiting project, with existing meta tickets – from which are some already closed ("Frühstück", "Mittagessen", etc.) – these encoding tickets (e.g. subformats) should not be added to the closed ones.

**Comment by jjeising** [comment]
Encoding tickets are always for all meta tickets in ordinary projects. We could discuss about putting tickets in a special state. But as other encoding tickets for closed meta tickets stay in _material needed_, I don't see any reason to do something special here.

Why are these tickets a problem?

**Comment by saerdnaer** [comment]
I this weekend's conference we initially had only master mp4 encoding tickets, so I manually deleted the subtickets and got a quite nice representation similar to this:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/40266/54885986-e965f900-4e82-11e9-8f07-b2ed7740fe7f.png">

When I later added the other encoding profile this view was reset, but I actually liked the old view – so I created this ticket. Feel free to close it, if you have another opinion.

**Comment by jjeising** [comment]
> so I manually deleted the subtickets

You shouldn't do that and you are only allowed to do that, because you are admin. Be careful! 🚧

> but I actually liked the old view – so I created this ticket.

Ok, completely changed requirements. We could maybe update the default view.

**Comment by a-tze** [comment]
Tried with CSS but selectors are not powerful enough.. the ticket li elements should have something like data-parent-state, then it's actually easy.

**Comment by jjeising** [comment]
> Tried with CSS but selectors are not powerful enough

I don't think filtering with CSS is a good idea, as these views are already heavy on database queries. Reducing the number of tickets loaded from the database can quite speed up these views.

**Comment by jjeising** [comment]
Closed in 8c1c814.
