### ISSUE TITLE
Check on dependee ticket state > dependent ticket state missing

### ISSUE THREAD

**Issue by a-tze** [crs-tools/tracker#208]
Currently, only profile priority keeps dependent tickets from reaching a "higher" state than the dependee ticket.

**Comment by pegro** [comment]
Can you give a hint how to reproduce the issue?

**Comment by a-tze** [comment]
The real world scenario is that you set the "needed state" lower than releasing, lets say postencoded. Then the depending ticket is given to postprocessing, releasing etc. even if the dependee ticket has not progressed so far. So for example, the mp3 file might come to releasing before MP4 master. Current countermeasure is to set the encoding profile priority of the dependee profile to High, but this is something that is often forgotten.
