### ISSUE TITLE
empty response when working with non existant ticketid

### ISSUE THREAD

**Issue by Garionion** [crs-tools/tracker#219]
When talking to the api, using a ticket id which is not existant, the api response is empty instead of a proper description/error code

**Comment by a-tze** [comment]
Depending on the API call, this might be intended. Please specify the API call(s).

**Comment by Garionion** [comment]
I had this issue when using [getTicketInfo](https://github.com/crs-tools/tracker/blob/master/src/Application/Controller/XMLRPC/Handler.php#L244).

**Comment by jjeising** [comment]
According to the code there should be an error. Needs testing.

**Comment by pegro** [comment]
Commit https://github.com/jjeising/framework/commit/b5d6144198cbb04c3c2578178f1156618bcc99b6 changed `Log::handleException()` to call `exit(255)`, which terminates the PHP processing. I consider this an API breakage. So either all users switch to using `Log::exception()` or the API change should be rolled back.

**Comment by jjeising** [comment]
> So either all users switch to using Log::exception() or the API change should be rolled back.

You're right. `handleException()` is only intended for `set_exception_handler` and should probably be protected or private, but I think [that's not possible with static methods](https://3v4l.org/Jm9SX). Should probably prefix this method with an underscore.
